/* =========================================================================
 * Dex entries: Eurasian residents, northern specialists and the regional
 * trophies — the ones people plan whole trips around.
 * ====================================================================== */
Birdex.addSpecies([

/* ---- Northern and montane specialists ---------------------------- */

{ id: 'clanut', n: "Clark's Nutcracker", sci: 'Nucifraga columbiana', fam: 'Crows & Jays', size: '27–30 cm', shape: 'corvid',
  c: ['#9aa0a8', '#b5bac2', '#22262c', '#22262c'],
  look: 'Pale grey crow-relative with black wings, a long dagger bill and flashing white in wing and tail.',
  habitat: 'High-elevation pine forest, timberline and mountain car parks.',
  range: 'The mountains of western North America.',
  food: 'Pine seeds, prised out of cones and carried in a pouch under the tongue.',
  nest: 'A conifer nest built in late winter, incubated through snow.',
  voice: 'A harsh, drawn-out grating "kra-a-a".',
  fact: 'It caches up to 30,000 seeds a year in thousands of separate spots and relocates most of them months later under snow.',
  r: { RCK: 3, PNW: 2, CAL: 2, SW: 2, CAN: 2, GPL: 1 }, sn: 'y' },

{ id: 'redcro', n: 'Red Crossbill', sci: 'Loxia curvirostra', fam: 'Finches', size: '14–20 cm', shape: 'finch',
  c: ['#b5451d', '#c9542a', '#a53a1a', '#5a5048'],
  look: 'A chunky finch whose bill tips cross over each other; males brick-red, females olive-yellow.',
  habitat: 'Conifer forest, wherever the cone crop is good this year.',
  range: 'Across the northern hemisphere, wandering nomadically.',
  food: 'Conifer seeds, levered out of closed cones with that crossed bill.',
  nest: 'Anywhere, any month — it breeds whenever cones are abundant, including midwinter.',
  voice: 'A hard "kip-kip-kip" given in flight.',
  fact: 'North America holds at least ten "call types", each with a differently sized bill matched to a different conifer.',
  r: { RCK: 2, PNW: 2, CAN: 2, NE: 2, CAL: 2, SW: 2, MEX: 2, MDW: 1, NEU: 2, EEU: 2, SEU: 1, UKI: 1, AK: 1, GPL: 1 }, sn: 'y' },

{ id: 'comred', n: 'Common Redpoll', sci: 'Acanthis flammea', fam: 'Finches', size: '12–14 cm', shape: 'finch',
  c: ['#8a7f70', '#f2efe8', '#c0392b', '#e8c34a'],
  look: 'A small streaky finch with a raspberry forehead patch, black chin and a tiny yellow bill.',
  habitat: 'Arctic scrub and boreal birch; southern feeders in irruption winters.',
  range: 'Circumpolar, moving south into the northern states and Europe some years.',
  food: 'Birch and alder catkin seeds.',
  nest: 'A cup low in Arctic willow, thickly lined with ptarmigan feathers.',
  voice: 'A dry rattling trill and buzzy notes from a bounding flock.',
  fact: 'It tunnels into snow to roost and can survive nights at −50 °C, storing seed in a throat pouch to digest in the dark.',
  r: { CAN: 3, AK: 3, NEU: 3, NE: 1, MDW: 1, GPL: 1, RCK: 1, EEU: 2, UKI: 1, PNW: 1 },
  sn: 'y', sr: { NE: 'w', MDW: 'w', GPL: 'w', RCK: 'w', UKI: 'w', PNW: 'w', EEU: 'w' } },

{ id: 'snobun', n: 'Snow Bunting', sci: 'Plectrophenax nivalis', fam: 'Longspurs & Snow Buntings', size: '15–19 cm', shape: 'sparrow',
  c: ['#c8b898', '#f4f2ec', '#e8dcd0', '#3a3f47'],
  look: 'A white bird with black wingtips and a rusty-buff wash in winter; breeding males are pure black and white.',
  habitat: 'Arctic rock fields in summer; windswept beaches, stubble and roadsides in winter.',
  range: 'Circumpolar Arctic, wintering across the northern United States and Europe.',
  food: 'Seeds and, in summer, insects.',
  nest: 'Deep in a rock crevice — so cold that the female must be fed by the male to stay on the eggs.',
  voice: 'A musical rippling twitter from a flock swirling like blown snow.',
  fact: 'It nests farther north than almost any land bird, including on the northern tip of Greenland.',
  r: { AK: 3, CAN: 3, NEU: 3, MDW: 2, NE: 2, GPL: 2, RCK: 1, UKI: 2, PNW: 1, EEU: 2 },
  sn: 'y', sr: { MDW: 'w', NE: 'w', GPL: 'w', RCK: 'w', UKI: 'w', PNW: 'w', EEU: 'w' } },

{ id: 'amepip', n: 'American Pipit', sci: 'Anthus rubescens', fam: 'Pipits & Wagtails', size: '14–17 cm', shape: 'sparrow',
  c: ['#8a8070', '#ded6c8', '#9a9082', '#3a3f47'],
  look: 'A slim, streaky, grey-brown ground bird that walks rather than hops, pumping its tail.',
  habitat: 'Alpine and Arctic tundra to breed; ploughed fields, shorelines and airfields in winter.',
  range: 'Northern and montane North America, wintering to Central America.',
  food: 'Insects and seeds picked off bare ground.',
  nest: 'A cup tucked under a tundra hummock.',
  voice: 'A sharp "pip-it" given overhead in flight.',
  fact: 'The tail-pumping walk separates it from every sparrow before you get close enough to see a feather.',
  r: { AK: 3, CAN: 3, RCK: 2, CAL: 3, TEX: 3, SE: 2, MDW: 2, MEX: 3, GPL: 2, MAT: 2, PNW: 2, FL: 2, SW: 3 },
  sn: 'y', sr: { AK: 's', CAN: 's', RCK: 's', NAE: 'w', NAC: 'w', SW: 'w', CAL: 'w', MEX: 'w', PNW: 'w' } },

/* ---- Regional trophies ------------------------------------------- */

{ id: 'flsjay', n: 'Florida Scrub-Jay', sci: 'Aphelocoma coerulescens', fam: 'Crows & Jays', size: '25–28 cm', shape: 'jay',
  c: ['#5a8fc4', '#d8d5cc', '#6a9fd6', '#22262c'],
  look: 'A pale blue-and-grey crestless jay with a whitish forehead and a long blue tail.',
  habitat: 'Florida oak scrub on ancient sand ridges — and nowhere else on earth.',
  range: 'Endemic to peninsular Florida; the state\'s only endemic bird species.',
  food: 'Acorns, insects and lizards; caches thousands of acorns in the sand each autumn.',
  nest: 'A twig cup low in a scrub oak, with grown offspring helping raise the brood.',
  voice: 'A rasping, scolding "shreep" from a lookout perch.',
  fact: 'Family groups post a sentinel while the rest feed, and the habitat needs regular fire — without burns, the jays vanish.',
  r: { FL: 1, SE: 0 }, sn: 'y' },

{ id: 'yebmag', n: 'Yellow-billed Magpie', sci: 'Pica nuttalli', fam: 'Crows & Jays', size: '43–54 cm', shape: 'corvid',
  c: ['#22262c', '#f2efe8', '#e8c34a', '#e8c34a'],
  look: 'A Black-billed Magpie with a bright yellow bill and bare yellow skin around the eye.',
  habitat: 'Oak savanna and ranchland of the Central Valley and coastal ranges.',
  range: 'Endemic to California — one of very few bird species restricted to a single US state.',
  food: 'Insects, carrion, acorns and grain.',
  nest: 'A domed stick nest in a valley oak, often in loose colonies.',
  voice: 'A nasal chatter, higher than a Black-billed Magpie\'s.',
  fact: 'West Nile virus killed close to half the world population in the mid-2000s; it is still recovering.',
  r: { CAL: 2, PNW: 0 }, sn: 'y' },

{ id: 'grekis', n: 'Great Kiskadee', sci: 'Pitangus sulphuratus', fam: 'Tyrant Flycatchers', size: '25–27 cm', shape: 'flycatcher',
  c: ['#a0522d', '#e8c34a', '#22262c', '#2b2e33'],
  look: 'A big bold flycatcher: black-and-white striped head, rufous wings and a brilliant lemon belly.',
  habitat: 'Riverside woodland, town parks and resacas of the Rio Grande valley.',
  range: 'South Texas through Mexico to Argentina.',
  food: 'Insects, lizards, fruit — and small fish, which it dives for like a kingfisher.',
  nest: 'A bulky domed ball of grass with a side entrance.',
  voice: 'A loud, ringing "kis-ka-DEE!" that names the bird.',
  fact: 'It is one of very few flycatchers that regularly plunge-dives for fish.',
  r: { TEX: 3, MEX: 4, SW: 0, FL: 0 }, sn: 'y' },

{ id: 'grnjay', n: 'Green Jay', sci: 'Cyanocorax yncas', fam: 'Crows & Jays', size: '25–29 cm', shape: 'jay',
  c: ['#4a9a5a', '#c8e05a', '#3a6fc4', '#22262c'],
  look: 'Lime-green body, yellow outer tail feathers and a blue-and-black head — like a tropical parrot with a jay\'s manners.',
  habitat: 'Thorn forest and riverside woods of the Rio Grande valley.',
  range: 'South Texas through Mexico into the Andes.',
  food: 'Insects, seeds, fruit and eggs.',
  nest: 'A twig cup in a dense thorny tree.',
  voice: 'A raucous mix of rattles, bells and dry "cheh-cheh-cheh" notes.',
  fact: 'Texas birds use small sticks as tools to prise bark loose — tool use is rare outside crows and ravens.',
  r: { TEX: 2, MEX: 3, SW: 0 }, sn: 'y' },

{ id: 'eletro', n: 'Elegant Trogon', sci: 'Trogon elegans', fam: 'Trogons', size: '28–30 cm', shape: 'trogon',
  c: ['#2f7a5a', '#c0392b', '#3d8a6a', '#e8c34a'],
  look: 'Metallic green above, crimson below, with a white chest band, a yellow bill and a long copper-barred tail.',
  habitat: 'Sycamore-lined canyons in the sky islands of southeast Arizona.',
  range: 'Mexico and Central America, reaching the United States only in a handful of Arizona canyons.',
  food: 'Large insects and fruit, snatched in a hover.',
  nest: 'An old woodpecker cavity in a sycamore.',
  voice: 'A hoarse, croaking series — "koa, koa, koa" — like a distant turkey.',
  fact: 'It is the single biggest reason birders drive to Madera and Cave Creek canyons every summer.',
  r: { SW: 1, MEX: 3, TEX: 0, CAL: 0 }, sn: 's', sr: { MEX: 'y' } },

{ id: 'painre', n: 'Painted Redstart', sci: 'Myioborus pictus', fam: 'Wood-Warblers', size: '13–15 cm', shape: 'warbler',
  c: ['#22262c', '#c0392b', '#2b2e33', '#2b2e33'],
  look: 'Glossy black with a scarlet belly and big white wing and tail patches, constantly fanned.',
  habitat: 'Pine-oak canyons in the mountains of the Southwest.',
  range: 'Arizona and New Mexico south through Mexico to Nicaragua.',
  food: 'Insects flushed out of foliage by flashing those white patches.',
  nest: 'A cup on a sheltered canyon bank or under a rock ledge.',
  voice: 'A rich, repeated "weeta-weeta-weeta-wee".',
  fact: 'Both sexes are equally bright and both sing — unusual among North American warblers.',
  r: { SW: 2, MEX: 3, TEX: 1, CAL: 0 }, sn: 's', sr: { MEX: 'y' } },

{ id: 'cacwre', n: 'Cactus Wren', sci: 'Campylorhynchus brunneicapillus', fam: 'Wrens', size: '18–23 cm', shape: 'wren',
  c: ['#8a7a5a', '#e0d6c4', '#f2efe8', '#4a4438'],
  look: 'A big, heavily spotted wren with a bold white eyebrow and a barred tail — the largest wren in the United States.',
  habitat: 'Cholla and saguaro desert, mesquite thickets and desert suburbs.',
  range: 'The southwestern United States and northern Mexico.',
  food: 'Insects, plus fruit and seeds; it rarely needs to drink.',
  nest: 'A football-sized grass ball built inside a cholla cactus, spines and all.',
  voice: 'A low, grating "chug-chug-chug-chug" like a car that will not start.',
  fact: 'Pairs build several extra nests as decoys and roosts, and defend the whole cluster year-round.',
  r: { SW: 4, MEX: 3, CAL: 2, TEX: 2, RCK: 1 }, sn: 'y' },

{ id: 'redegr', n: 'Reddish Egret', sci: 'Egretta rufescens', fam: 'Herons & Egrets', size: '68–82 cm', shape: 'heron',
  c: ['#8a5f6a', '#9a6f7a', '#c86a6a', '#e8a5a5'],
  look: 'A shaggy slate-and-rust heron with a pink bill tipped black; a white morph also occurs.',
  habitat: 'Shallow coastal lagoons and salt flats — almost never inland.',
  range: 'The Gulf and Florida coasts, the Caribbean and Mexico.',
  food: 'Fish, herded by a wild dancing run with wings raised to cast shade.',
  nest: 'A stick platform in a coastal mangrove colony.',
  voice: 'Low guttural croaks.',
  fact: 'The rarest heron in North America — plume hunters nearly finished it, and the US population is still only in the low thousands.',
  r: { TEX: 2, FL: 2, MEX: 2, SE: 1, CAL: 1 }, sn: 'y' },

{ id: 'calcon', n: 'California Condor', sci: 'Gymnogyps californianus', fam: 'New World Vultures', size: '109–140 cm', shape: 'vulture',
  c: ['#22262c', '#2b2e33', '#e8a24a', '#c8b898'],
  look: 'Colossal black vulture with white underwing triangles, a bare orange head and numbered wing tags.',
  habitat: 'Mountain and canyon country with cliffs for roosting and open range for carrion.',
  range: 'A tiny reintroduced population in California, Arizona, Utah and Baja California.',
  food: 'Large carrion — deer, cattle, marine mammals on the coast.',
  nest: 'A cave or cliff cavity; a single egg every other year.',
  voice: 'Hisses and grunts only.',
  fact: 'Every bird alive descends from 27 individuals taken into captivity in 1987; lead poisoning from ammunition is still the main killer.',
  r: { CAL: 0, SW: 0, RCK: 0 }, sn: 'y' },

/* ---- Eurasian residents ------------------------------------------ */

{ id: 'eurrob', n: 'European Robin', sci: 'Erithacus rubecula', fam: 'Chats & Old World Flycatchers', size: '12–14 cm', shape: 'songbird',
  c: ['#7a7a62', '#e8dcd0', '#e0562a', '#2b2e33'],
  look: 'Round, big-eyed brown bird with a burnt-orange face and breast bordered in blue-grey.',
  habitat: 'Woodland, hedges, parks and every garden with a freshly dug flowerbed.',
  range: 'Across Europe, North Africa and western Asia.',
  food: 'Worms, insects and berries, often taken from ground a gardener has just turned.',
  nest: 'A cup in a bank, ivy, or a discarded kettle — it is famously willing.',
  voice: 'A wistful, silvery warble sung all year, including at night under street lights.',
  fact: 'It defends its territory year-round and can navigate using a light-driven magnetic sense in its eyes.',
  r: { EU: 5, UKI: 5, WEU: 5, SEU: 4, EEU: 4, NEU: 3 }, sn: 'y' },

{ id: 'combla', n: 'Common Blackbird', sci: 'Turdus merula', fam: 'Thrushes', size: '24–29 cm', shape: 'thrush',
  c: ['#22262c', '#2b2e33', '#33373d', '#e8a832'],
  look: 'Males jet black with a bright orange-yellow bill and eye-ring; females dark brown and faintly streaked.',
  habitat: 'Gardens, woodland, parks and farmland across Europe.',
  range: 'Europe, North Africa and Asia; introduced to Australia and New Zealand.',
  food: 'Worms, insects and autumn fruit.',
  nest: 'A mud-lined cup in a hedge or creeper.',
  voice: 'A rich, unhurried, fluting song from a rooftop at dusk — and a hysterical rattling alarm.',
  fact: 'It is the European equivalent of the American Robin in every way except colour — and they are close cousins.',
  r: { EU: 5, UKI: 5, WEU: 5, SEU: 4, EEU: 4, NEU: 3 }, sn: 'y' },

{ id: 'blutit', n: 'Eurasian Blue Tit', sci: 'Cyanistes caeruleus', fam: 'Chickadees & Titmice', size: '11–12 cm', shape: 'songbird',
  c: ['#5a8fc4', '#e8dc5a', '#3a6fb5', '#2b2e33'],
  look: 'Tiny, acrobatic, with a sky-blue cap and wings, yellow underparts and a black eye-stripe.',
  habitat: 'Deciduous woodland, hedgerows and every garden feeder in Europe.',
  range: 'Europe and western Asia.',
  food: 'Caterpillars in spring, seeds and peanuts in winter.',
  nest: 'A moss cup in a hole or nest box; up to 12 eggs, timed exactly to the oak caterpillar peak.',
  voice: 'A scolding "tsee-tsee-tsit" and a silvery trill.',
  fact: 'British blue tits famously learned to peel foil milk-bottle tops, and the habit spread bird to bird across the country.',
  r: { EU: 5, UKI: 5, WEU: 5, SEU: 4, EEU: 4, NEU: 3 }, sn: 'y' },

{ id: 'greti', n: 'Great Tit', sci: 'Parus major', fam: 'Chickadees & Titmice', size: '13–15 cm', shape: 'songbird',
  c: ['#7a8a5a', '#e8dc5a', '#22262c', '#2b2e33'],
  look: 'Yellow below with a black stripe down the belly, a glossy black head and white cheeks.',
  habitat: 'Woodland, parks and gardens.',
  range: 'Across Europe and Asia to Japan.',
  food: 'Insects, seeds and nuts; will hammer open a hazelnut wedged in a crevice.',
  nest: 'A cavity or box lined with moss and hair.',
  voice: 'A ringing, bicycle-pump "tea-cher, tea-cher".',
  fact: 'The width of the black belly stripe advertises male quality — and females pick accordingly.',
  r: { EU: 5, UKI: 5, WEU: 5, SEU: 4, EEU: 5, NEU: 4 }, sn: 'y' },

{ id: 'eurmag', n: 'Eurasian Magpie', sci: 'Pica pica', fam: 'Crows & Jays', size: '44–46 cm', shape: 'corvid',
  c: ['#22262c', '#f2efe8', '#2f5fa8', '#1a1d21'],
  look: 'Black and white with a long iridescent green-blue tail and a bold, confident walk.',
  habitat: 'Farmland with hedges, parks, gardens and city edges.',
  range: 'Europe and much of temperate Asia.',
  food: 'Insects, carrion, eggs, scraps and grain.',
  nest: 'A big domed stick nest with a roof, high in a tree.',
  voice: 'A hard, machine-gun chatter.',
  fact: 'It passed the mirror mark test — one of very few non-mammals shown to recognise itself.',
  r: { EU: 4, UKI: 4, WEU: 4, SEU: 3, EEU: 4, NEU: 3 }, sn: 'y' },

{ id: 'eurjay', n: 'Eurasian Jay', sci: 'Garrulus glandarius', fam: 'Crows & Jays', size: '32–35 cm', shape: 'jay',
  c: ['#b58a6a', '#d8c9b8', '#5a8fc4', '#22262c'],
  look: 'Pinkish-brown jay with a white rump, black moustache and an electric-blue barred wing patch.',
  habitat: 'Oak and mixed woodland, wooded parks.',
  range: 'Europe, North Africa and across Asia to Japan.',
  food: 'Acorns above all, plus insects, eggs and nestlings.',
  nest: 'A twig cup hidden in a tree fork.',
  voice: 'A harsh, tearing screech — usually the first sign anyone is in the wood.',
  fact: 'A single jay buries thousands of acorns a year; oak woods spread northwards after the ice age at jay speed.',
  r: { EU: 3, UKI: 3, WEU: 4, SEU: 3, EEU: 4, NEU: 2 }, sn: 'y' },

{ id: 'eurwre', n: 'Eurasian Wren', sci: 'Troglodytes troglodytes', fam: 'Wrens', size: '9–10 cm', shape: 'wren',
  c: ['#8a6a4a', '#c8b898', '#a08a6a', '#4a4438'],
  look: 'A tiny round brown bird, barred and cocked-tailed, usually creeping through the undergrowth like a mouse.',
  habitat: 'Woodland undergrowth, hedge bottoms, walls, sea cliffs and gardens.',
  range: 'Across Europe, North Africa and Asia; the only wren outside the Americas.',
  food: 'Insects and spiders hunted in dense cover.',
  nest: 'A domed moss ball; the male builds several and the female picks one to line.',
  voice: 'An explosively loud song — 100 notes in five seconds from a 9-gram bird.',
  fact: 'In hard winters dozens roost together in one nest box for warmth; over 60 have been counted in a single box.',
  r: { EU: 4, UKI: 5, WEU: 4, SEU: 3, EEU: 3, NEU: 3 }, sn: 'y' },

{ id: 'comcha', n: 'Common Chaffinch', sci: 'Fringilla coelebs', fam: 'Finches', size: '14–16 cm', shape: 'finch',
  c: ['#8a6a5a', '#d99a8a', '#5a7fa8', '#a5abb5'],
  look: 'Males have a blue-grey cap, pink face and breast, and bold double white wingbars.',
  habitat: 'Woodland, farmland hedges, parks and gardens.',
  range: 'Europe, North Africa and western Asia.',
  food: 'Seeds and insects, mostly taken on the ground.',
  nest: 'A beautifully camouflaged lichen-covered cup in a fork.',
  voice: 'A cheerful accelerating rattle ending in a flourish — with strong regional dialects.',
  fact: 'Its dialects were the first ever mapped in a wild bird, in the 1950s.',
  r: { EU: 5, UKI: 5, WEU: 5, SEU: 4, EEU: 4, NEU: 4 }, sn: 'y' },

{ id: 'eurgol', n: 'European Goldfinch', sci: 'Carduelis carduelis', fam: 'Finches', size: '12–13 cm', shape: 'finch',
  c: ['#a08a6a', '#e8dcd0', '#c0392b', '#e8dcd0'],
  look: 'A gold-winged finch with a red face, black-and-white head and a broad yellow wing flash.',
  habitat: 'Thistly waste ground, orchards, hedgerows and gardens with nyjer feeders.',
  range: 'Europe, North Africa and western Asia; introduced to Australia and New Zealand.',
  food: 'Thistle and teasel seeds, extracted with a long fine bill.',
  nest: 'A neat cup high in a tree fork.',
  voice: 'A liquid, tinkling twitter — the flock is often called a "charm".',
  fact: 'The long bill lets it reach deep into teasel heads, which almost no other finch can manage.',
  r: { EU: 4, UKI: 4, WEU: 4, SEU: 4, EEU: 3, NEU: 2 }, sn: 'y' },

{ id: 'eurbul', n: 'Eurasian Bullfinch', sci: 'Pyrrhula pyrrhula', fam: 'Finches', size: '14–17 cm', shape: 'finch',
  c: ['#5a5f66', '#c94a5a', '#22262c', '#2b2e33'],
  look: 'A thickset finch with a black cap and bib, grey back, white rump and a rose-red breast on males.',
  habitat: 'Woodland edge, thick hedges, orchards and quiet gardens.',
  range: 'Across Europe and northern Asia.',
  food: 'Buds, seeds and berries; orchards once treated it as a pest for stripping fruit buds.',
  nest: 'A flimsy twig platform in a dense shrub.',
  voice: 'A soft, mournful, piping "peew" — easily missed.',
  fact: 'It carries food to the young in special throat pouches, a trick almost unique among finches.',
  r: { EU: 3, UKI: 3, WEU: 3, NEU: 3, EEU: 3, SEU: 2 }, sn: 'y' },

{ id: 'lottit', n: 'Long-tailed Tit', sci: 'Aegithalos caudatus', fam: 'Long-tailed Tits', size: '13–15 cm', shape: 'songbird',
  c: ['#c8a8b5', '#f2efe8', '#22262c', '#2b2e33'],
  look: 'A ball of fluff with a tail longer than its body, pink, black and white, always in chattering flocks.',
  habitat: 'Hedgerows, scrub and woodland edge.',
  range: 'Across Europe and Asia.',
  food: 'Tiny insects and spiders.',
  nest: 'An elastic domed purse of moss, lichen and up to 2,000 feathers, bound with spider silk.',
  voice: 'A constant thin "tsirrup" as the flock moves through a hedge.',
  fact: 'Failed breeders help feed a relative\'s chicks instead — one of the clearest cases of helper behaviour in Europe.',
  r: { EU: 3, UKI: 4, WEU: 3, SEU: 3, EEU: 3, NEU: 2 }, sn: 'y' },

{ id: 'comchi', n: 'Common Chiffchaff', sci: 'Phylloscopus collybita', fam: 'Leaf Warblers', size: '10–12 cm', shape: 'warbler',
  c: ['#7d8a6a', '#ddd9c8', '#8a9670', '#3a3f47'],
  look: 'A small olive-brown warbler with dark legs and a faint eyebrow — plain enough that the song is the identification.',
  habitat: 'Woodland with a shrub layer, scrub, parks and gardens.',
  range: 'Europe and western Asia, wintering around the Mediterranean and in Africa.',
  food: 'Small insects gleaned from leaves, often with a downward tail-flick.',
  nest: 'A domed nest low in brambles or nettles.',
  voice: 'Its own name repeated — "chiff-chaff-chiff-chaff" — one of the first songs of spring.',
  fact: 'Chiffchaff and Willow Warbler are nearly identical to look at and completely different to listen to.',
  r: { EU: 4, UKI: 4, WEU: 4, SEU: 4, EEU: 4, NEU: 3 }, sn: 'y', sr: { NEU: 's', EEU: 's', WEU: 's', UKI: 's' } },

{ id: 'goldcr', n: 'Goldcrest', sci: 'Regulus regulus', fam: 'Kinglets', size: '8–9 cm', shape: 'warbler',
  c: ['#7d8a6a', '#ddd9c8', '#e8c34a', '#2b2e33'],
  look: 'Europe\'s smallest bird: olive-green with a black-bordered gold crown stripe and a tiny needle bill.',
  habitat: 'Conifer forest, churchyard yews, gardens with spruce.',
  range: 'Across Europe and temperate Asia.',
  food: 'Minute insects and spiders taken from needle clusters.',
  nest: 'A hammock of moss and cobweb slung under a conifer branch.',
  voice: 'An extremely high, thin "see-see-see" that many adults cannot hear at all.',
  fact: 'It weighs about as much as a 20p coin, yet North Sea populations cross open water on migration.',
  r: { EU: 3, UKI: 4, WEU: 3, NEU: 3, EEU: 3, SEU: 2 }, sn: 'y' },

{ id: 'woopig', n: 'Common Wood Pigeon', sci: 'Columba palumbus', fam: 'Pigeons & Doves', size: '38–44 cm', shape: 'pigeon',
  c: ['#8b929c', '#c8b8b0', '#5a8a9a', '#e8a832'],
  look: 'A big grey pigeon with a white neck patch, pink breast and a broad white wing bar in flight.',
  habitat: 'Farmland, woods, parks and city squares.',
  range: 'Across Europe, North Africa and western Asia.',
  food: 'Crops, seeds, buds and berries — a serious agricultural pest in places.',
  nest: 'A flimsy stick platform in a tree.',
  voice: 'A husky five-note coo, often heard as "take TWO cows, Taffy".',
  fact: 'Both parents feed the young on "crop milk", a protein-rich secretion from the gullet lining.',
  r: { EU: 5, UKI: 5, WEU: 5, SEU: 4, EEU: 4, NEU: 3 }, sn: 'y' },

{ id: 'comkin', n: 'Common Kingfisher', sci: 'Alcedo atthis', fam: 'Kingfishers', size: '16–17 cm', shape: 'kingfisher',
  c: ['#2f8fb5', '#c96a2a', '#3aa5d6', '#2b2e33'],
  look: 'A jewel: electric blue above, burnt orange below, with a dagger bill and stubby tail.',
  habitat: 'Slow clear rivers, canals and lakes with overhanging perches and earth banks.',
  range: 'Europe, North Africa and Asia to the Solomon Islands.',
  food: 'Small fish, taken by diving from a perch or a brief hover.',
  nest: 'A tunnel up to 1 m long in a river bank, floored with fish bones.',
  voice: 'A piercing high whistle, usually all you get as a blue streak vanishes downstream.',
  fact: 'Hard winters that freeze rivers can wipe out most of a national population in a single season.',
  r: { EU: 2, UKI: 2, WEU: 2, SEU: 3, EEU: 2, NEU: 1 }, sn: 'y' },

{ id: 'greher2', n: 'Grey Heron', sci: 'Ardea cinerea', fam: 'Herons & Egrets', size: '84–102 cm', shape: 'heron',
  c: ['#8b929c', '#c8ccd2', '#22262c', '#e8c34a'],
  look: 'A tall grey heron with a white head, black eyebrow plume and a heavy yellow dagger bill.',
  habitat: 'Rivers, lakes, estuaries, ditches and garden ponds.',
  range: 'Across Europe, Asia and Africa.',
  food: 'Fish, frogs, voles and ducklings.',
  nest: 'A stick platform in a treetop heronry, occupied from February.',
  voice: 'A harsh, grating "fraank" as it lifts off.',
  fact: 'British heronries have been counted every year since 1928 — the longest-running bird survey in the world.',
  r: { EU: 3, UKI: 4, WEU: 3, SEU: 3, EEU: 3, NEU: 2 }, sn: 'y' },

{ id: 'mutswa', n: 'Mute Swan', sci: 'Cygnus olor', fam: 'Ducks & Geese', size: '125–160 cm', shape: 'swan',
  c: ['#f4f2ec', '#ffffff', '#e0562a', '#e0562a'],
  look: 'A huge white swan with an orange bill, black knob at the base and a gracefully curved neck.',
  habitat: 'Rivers, lakes, canals and sheltered coasts.',
  range: 'Europe and western Asia; introduced to North America, where it is now a problem species.',
  food: 'Aquatic vegetation, reached by upending.',
  nest: 'A vast mound of reed at the water\'s edge.',
  voice: 'Not mute at all — snorts, hisses, and a loud throbbing of the wings in flight.',
  fact: 'A defending male can break a person\'s arm, and North American populations are culled for damaging wetlands.',
  r: { EU: 3, UKI: 4, WEU: 3, EEU: 2, NEU: 3, SEU: 1, NE: 2, MAT: 2, MDW: 1 }, sn: 'y' },

{ id: 'eurcoo', n: 'Eurasian Coot', sci: 'Fulica atra', fam: 'Rails & Coots', size: '36–42 cm', shape: 'rail',
  c: ['#33373d', '#4b5058', '#22262c', '#f4f2ec'],
  look: 'A sooty black waterbird with a brilliant white bill and forehead shield and a red eye.',
  habitat: 'Lakes, reservoirs, park ponds and slow rivers.',
  range: 'Europe, Asia, North Africa and Australia.',
  food: 'Water plants, plus insects and small fish.',
  nest: 'A bulky floating platform among reeds.',
  voice: 'An explosive, metallic "kowk".',
  fact: 'Coots fight viciously — territorial disputes are a wild business of splashing feet and raised wings.',
  r: { EU: 4, UKI: 4, WEU: 4, SEU: 4, EEU: 3, NEU: 2 }, sn: 'y' },

{ id: 'combuz', n: 'Common Buzzard', sci: 'Buteo buteo', fam: 'Hawks & Eagles', size: '46–58 cm', shape: 'raptor',
  c: ['#6a5a4a', '#e0d6c4', '#8a7a62', '#e8c34a'],
  look: 'A broad-winged brown raptor, hugely variable from near-black to nearly white, soaring on raised wings.',
  habitat: 'Farmland with woods, moorland edge, motorway verges.',
  range: 'Across Europe and into Asia.',
  food: 'Voles, rabbits, worms and carrion — often walking on a ploughed field.',
  nest: 'A stick nest in a tall tree, decorated with fresh greenery.',
  voice: 'A far-carrying, plaintive mewing "pee-yaaa".',
  fact: 'Persecution nearly removed it from lowland Britain; it is now the commonest raptor there.',
  r: { EU: 3, UKI: 3, WEU: 4, SEU: 3, EEU: 3, NEU: 2 }, sn: 'y' },

{ id: 'redkit', n: 'Red Kite', sci: 'Milvus milvus', fam: 'Hawks & Eagles', size: '60–70 cm', shape: 'raptor',
  c: ['#a0522d', '#c96a4a', '#c8ccd2', '#e8c34a'],
  look: 'Rusty-red raptor with long angled wings, white wing patches and a deeply forked tail that twists constantly.',
  habitat: 'Wooded farmland, valleys and open hills.',
  range: 'Western Europe, with the world stronghold in Wales, England, Germany and Spain.',
  food: 'Carrion, worms and scraps; a scavenger far more than a hunter.',
  nest: 'A stick nest in a tall tree, often decorated with rubbish and plastic.',
  voice: 'A high, quavering, mewing whistle.',
  fact: 'Once so common it scavenged Tudor London\'s streets, then poisoned to near-extinction in Britain; reintroduction has been a landmark success.',
  r: { UKI: 2, WEU: 2, SEU: 2, EEU: 1, NEU: 1 }, sn: 'y' },

{ id: 'norlap', n: 'Northern Lapwing', sci: 'Vanellus vanellus', fam: 'Plovers', size: '28–33 cm', shape: 'plover',
  c: ['#2f5a4a', '#f4f2ec', '#22262c', '#2b2e33'],
  look: 'Iridescent green-black above, white below, with a wispy upswept crest and broad rounded wings.',
  habitat: 'Wet meadows, ploughed fields, marshes and coastal grazing.',
  range: 'Across Europe and temperate Asia.',
  food: 'Worms and insects taken with the plover run-and-tilt.',
  nest: 'A scrape in a field — badly exposed to modern farm machinery.',
  voice: 'A wheezy, electronic "pee-wit", which is its other name.',
  fact: 'Its floppy, tumbling display flight in early spring is one of the great sights of a European farmland morning.',
  r: { EU: 3, UKI: 3, WEU: 3, EEU: 3, NEU: 2, SEU: 2 }, sn: 'y', sr: { NEU: 's', EEU: 's' } },

{ id: 'comswi', n: 'Common Swift', sci: 'Apus apus', fam: 'Swifts', size: '16–17 cm', shape: 'swift',
  c: ['#3a3530', '#4a443c', '#e8e4dc', '#2b2e33'],
  look: 'An all-dark, scythe-winged bird with a small pale throat, screaming over rooftops on summer evenings.',
  habitat: 'The sky above towns; nests in roof cavities and church towers.',
  range: 'Breeds across Europe and Asia, winters in sub-Saharan Africa.',
  food: 'Aerial plankton — insects and spiders drifting on the wind.',
  nest: 'A shallow saucer of airborne material glued with saliva in a roof space.',
  voice: 'A piercing, exhilarating scream from low-flying parties.',
  fact: 'A young swift may not land again for two or three years — it eats, sleeps and mates on the wing.',
  r: { EU: 4, UKI: 4, WEU: 4, SEU: 4, EEU: 4, NEU: 3 }, sn: 's' },

{ id: 'whisto', n: 'White Stork', sci: 'Ciconia ciconia', fam: 'Storks', size: '100–115 cm', shape: 'stork',
  c: ['#f4f2ec', '#ffffff', '#22262c', '#c0392b'],
  look: 'A tall white stork with black flight feathers and long red bill and legs.',
  habitat: 'Wet meadows, farmland and marshes; nests on roofs, chimneys and poles.',
  range: 'Europe, North Africa and western Asia, wintering in Africa.',
  food: 'Frogs, insects, rodents and worms.',
  nest: 'An enormous stick nest on a village roof or platform, reused for generations.',
  voice: 'Voiceless apart from loud bill-clattering at the nest.',
  fact: 'A stork shot in Germany in 1822 carrying a central African spear was the first hard proof that birds migrate to Africa.',
  r: { SEU: 3, EEU: 3, WEU: 2, NEU: 1, UKI: 0 }, sn: 's', sr: { SEU: 'y' } },

{ id: 'eurbee', n: 'European Bee-eater', sci: 'Merops apiaster', fam: 'Bee-eaters', size: '27–29 cm', shape: 'beeeater',
  c: ['#a0522d', '#5ac4d6', '#e8c34a', '#2b2e33'],
  look: 'A riot of chestnut, gold and turquoise with a black eye-stripe and long central tail pins.',
  habitat: 'Open warm country with sandy banks — river valleys, quarries, farmland.',
  range: 'Southern Europe and western Asia, wintering in Africa.',
  food: 'Bees, wasps and dragonflies caught on the wing.',
  nest: 'A tunnel up to 2 m long dug into a sandy bank, in colonies.',
  voice: 'A liquid, rolling "prrrp" given constantly in flight — usually heard before seen.',
  fact: 'It de-stings each bee by rubbing it against a perch before swallowing, and eats hundreds a day.',
  r: { SEU: 3, EEU: 2, WEU: 1, UKI: 0, NEU: 0 }, sn: 's' },

{ id: 'hoopoe', n: 'Eurasian Hoopoe', sci: 'Upupa epops', fam: 'Hoopoes', size: '25–32 cm', shape: 'hoopoe',
  c: ['#c8865a', '#e0b898', '#22262c', '#3a3f47'],
  look: 'Pinkish-buff with zebra-striped wings and a spectacular fan crest it raises on landing.',
  habitat: 'Warm open country with bare ground — orchards, vineyards, pasture, olive groves.',
  range: 'Southern Europe, Africa and Asia.',
  food: 'Insects and grubs probed from soft ground with a long decurved bill.',
  nest: 'A cavity in a tree or wall; the nest becomes famously foul-smelling, which deters predators.',
  voice: 'A soft, far-carrying "oop-oop-oop" that names the bird.',
  fact: 'Nestlings can spray faeces at intruders, and the female produces a foul-smelling secretion — chemical nest defence.',
  r: { SEU: 3, EEU: 2, WEU: 2, UKI: 0, NEU: 0, MEX: 0 }, sn: 's', sr: { SEU: 'y' } },

{ id: 'comcuc', n: 'Common Cuckoo', sci: 'Cuculus canorus', fam: 'Cuckoos', size: '32–34 cm', shape: 'cuckoo',
  c: ['#8b929c', '#eceff2', '#a5abb5', '#e8c34a'],
  look: 'Slim grey bird with barred underparts and long tail; looks startlingly like a Sparrowhawk in flight.',
  habitat: 'Reedbeds, moorland, farmland and woodland edge.',
  range: 'Across Europe and Asia, wintering in Africa.',
  food: 'Insects, especially hairy caterpillars that other birds refuse.',
  nest: 'None — the female lays single eggs in the nests of pipits, warblers and dunnocks.',
  voice: 'The famous two-note "cuc-koo", the traditional sound of European spring.',
  fact: 'Different female lineages specialise on different hosts and lay eggs matching that host\'s pattern.',
  r: { EU: 2, UKI: 2, WEU: 2, SEU: 2, EEU: 3, NEU: 2 }, sn: 's' }

]);
